### ISSUE TITLE
Won't go away: "I need to meet the Informant in the Penumbra District near the Medical Clinic."

### ISSUE THREAD

**Issue by jmccorm** [JamesB192/Shadowrun-Unlimited-rip#11]
Once I acquired the Medical Clinic mission in the Penumbra District, even after answering the phone and having the conversation, the mission (listed on the left hand side of the screen) didn't go away. Changing maps, and exiting/reloading didn't help.

Was using the build on Steam, which from memory, was October 17th 2017 (version 1.201).

Hope this helps, great game. (Perhaps needs added variety in the low-level missions.)

**Comment by JamesB192** [comment]
1.201 was Southwinds from about sep 10 2014. if you were playing mine from since April the message would have gone away when you talked to the tipster. If I remember correctly the message _never_ goes away in Southwinds version.

**Comment by jmccorm** [comment]
Apologies! Closing, and thank you for sharing those important details.
