### ISSUE TITLE
Spelling errors in game description

### ISSUE THREAD

**Issue by ChristophFranzen** [JamesB192/Shadowrun-Unlimited-rip#42]
`story.story.txt`, line _4370_:
`Steam workshop dowloaders should work with the fomer URL.\n\nMaintainence?`
Shouldn't that be instead:
_Steam workshop dow **n** loaders should work with the fo **r** mer URL.\n\nMaint ~~ai~~ **e** n ~~e~~ **a** nce?_
`Steam workshop downloaders should work with the former URL.\n\nMaintenance?`

**Comment by JamesB192** [comment]
The next release should have this., pushed to hkci and stableish. The impatient should wait.
