### ISSUE TITLE
doc wagon on run crash

### ISSUE THREAD

**Issue by bdfworks** [JamesB192/Shadowrun-Unlimited-rip#6]
during run, if main runner dies on non-story run with doc wagon contract, game crashes instead of re-spawning

**Comment by JamesB192** [comment]
I can't make this go away atm. Everything I have tried is futile including going back to versions where I distinctly remember this was not an issue. I think it is an engine bug. I need info on why PC0 is vanishing _before_ the DocWagon conversation starts.

**Comment by JamesB192** [comment]
I just triggered thins in Wylies Shadowrun Unlimited. I pretty sure I don't remember it being there before.

**Comment by JamesB192** [comment]
What seems to trigger it is that there is no other player controls member on Shadowrunner team when there is such a member you got the 3 round countdown.
